### PR TITLE
Update snapshots

### PR DESCRIPTION
**Pull request by kfcampbell**
This PR resolves the build failures we're seeing on this repo. It was created by running `npx ava -u` on Node v18.14.2.

----

### Before the change?

* Running `npm run test` is failing on the CI build.

### After the change?

* Running `npm run test` succeeds!

### Other information

* N/A

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/master/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:  

* N/A

### Pull request type

 
 

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by kfcampbell** [comment]
Hmm...I have Node v18.12.1 installed locally and cannot reproduce this error.

**Comment by kfcampbell** [comment]
Setting `AVA_FORCE_CI` to `ci` is also producing a clean test run for me.

**Comment by wolfy1339** [comment]
I can reproduce locally myself. Node v18.14.2

**Comment by kfcampbell** [comment]
@wolfy1339 thanks a bunch! I'm now seeing this error when using that Node version.

**Pull request merged**
